def setup(pw_incr_us: int, hw: int) -> int: ...
def shutdown() -> None: ...
def set_loglevel(level: int) -> None: ...

def init_channel(channel: int, subcycle_time_us: int) -> int: ...
def clear_channel(channel: int) -> int: ...
def clear_channel_gpio(channel: int, gpio: int) -> int: ...
def print_channel(channel: int) -> int: ...

def add_channel_pulse(channel: int, gpio: int, width_start: int, width: int) -> int: ...
def get_error_message() -> str: ...
def set_softfatal(enabled: int) -> None: ...

def is_setup() -> int: ...
def is_channel_initialized(channel: int) -> int: ...
def get_pulse_incr_us() -> int: ...
def get_channel_subcycle_time_us(channel: int) -> int: ...

DELAY_VIA_PWM = 0
DELAY_VIA_PCM = 1

LOG_LEVEL_DEBUG = 0
LOG_LEVEL_ERRORS = 1
LOG_LEVEL_DEFAULT = LOG_LEVEL_DEBUG

# Default subcycle time
SUBCYCLE_TIME_US_DEFAULT = 20000

# Subcycle minimum. We kept seeing no signals and strange behavior of the RPi
SUBCYCLE_TIME_US_MIN = 3000

# Default pulse-width-increment-granularity
PULSE_WIDTH_INCREMENT_GRANULARITY_US_DEFAULT = 10
